// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArr99WYCjLNgXH7ot0HWigdl6VZWpczm8',
    appId: '1:1015216276954:web:d3b5fd2fee1ec2d3a62ce3',
    messagingSenderId: '1015216276954',
    projectId: 'le-bon-randonneur',
    authDomain: 'le-bon-randonneur.firebaseapp.com',
    storageBucket: 'le-bon-randonneur.appspot.com',
    measurementId: 'G-060BNVJ7JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs6gv7uHJX2InpQ6OBs7po_c6lbulx5yo',
    appId: '1:1015216276954:android:d50b1957f69e7571a62ce3',
    messagingSenderId: '1015216276954',
    projectId: 'le-bon-randonneur',
    storageBucket: 'le-bon-randonneur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pxEzj3UIl54jMq8C9O62sHBrL2FqNYc',
    appId: '1:1015216276954:ios:6ccbd52cb7864ddda62ce3',
    messagingSenderId: '1015216276954',
    projectId: 'le-bon-randonneur',
    storageBucket: 'le-bon-randonneur.appspot.com',
    iosClientId: '1015216276954-8c5rl8n5u59l9v1e4hqppu6dlc2h4r28.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationRandonneur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7pxEzj3UIl54jMq8C9O62sHBrL2FqNYc',
    appId: '1:1015216276954:ios:6ccbd52cb7864ddda62ce3',
    messagingSenderId: '1015216276954',
    projectId: 'le-bon-randonneur',
    storageBucket: 'le-bon-randonneur.appspot.com',
    iosClientId: '1015216276954-8c5rl8n5u59l9v1e4hqppu6dlc2h4r28.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationRandonneur',
  );
}
